services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: balance_ledger
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080