// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateLedger(ctx context.Context, arg CreateLedgerParams) (Ledger, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteLedger(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetBalanceByUser(ctx context.Context, userID string) (int64, error)
	GetLedgerByID(ctx context.Context, id string) (Ledger, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListLedgerByUser(ctx context.Context, arg ListLedgerByUserParams) ([]Ledger, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateLedger(ctx context.Context, arg UpdateLedgerParams) (Ledger, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
